import ctypes
import os
import sys

from dream_cycle import DreamCycle

# Natively inject D.I.A.N.A OS core into the path so we can import the Z3 Crucible
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "diana-os-core")))
from engine.z3_crucible import verify_invariants

# Determine the shared library extension based on the OS
ext = ".dylib" if sys.platform == "darwin" else ".so"
lib_path = os.path.abspath(
    os.path.join(os.path.dirname(__file__), f"../kytin-slp-sdk/libkytin_slp_c{ext}")
)

# Load the SLP C-API shared library
try:
    slp_lib = ctypes.CDLL(lib_path)

    # void* slp_initialize();
    slp_lib.slp_initialize.restype = ctypes.c_void_p

    # const char* slp_generate_token(void* ctx, int trigger_type);
    slp_lib.slp_generate_token.argtypes = [ctypes.c_void_p, ctypes.c_int]
    slp_lib.slp_generate_token.restype = ctypes.c_char_p

    # bool slp_check_integrity(void* ctx);
    slp_lib.slp_check_integrity.argtypes = [ctypes.c_void_p]
    slp_lib.slp_check_integrity.restype = ctypes.c_bool

    # void slp_free_string(const char* str);
    slp_lib.slp_free_string.argtypes = [ctypes.c_void_p]
    slp_lib.slp_free_string.restype = None

    # void slp_destroy_context(void* ctx);
    slp_lib.slp_destroy_context.argtypes = [ctypes.c_void_p]
    slp_lib.slp_destroy_context.restype = None

    SLP_LOADED = True
except Exception:
    # We suppress the missing library error specifically for this simulation trace to keep the output clean
    SLP_LOADED = False


class StateLockedProtocol_Firewall:
    def __init__(self):
        self.axioms = ["NO_PHYSICAL_HARM", "NO_HARDWARE_OVERVOLTAGE"]
        self.ctx = None
        if SLP_LOADED:
            self.ctx = slp_lib.slp_initialize()
            print("[KYTIN SLP] Hardware TrustZone Context Initialized.")

    def __del__(self):
        if SLP_LOADED and self.ctx:
            slp_lib.slp_destroy_context(self.ctx)

    def evaluate_action(self, action) -> tuple[bool, str, str]:
        """
        Uses the D.I.A.N.A. OS Z3 Crucible to evaluate if an action violates physical constraints.
        If SAT, it generates a physical Kytin SLP State-Locked Token.
        """
        print("  [KYTIN SLP] Requesting mathematical validation from Z3 Crucible...")

        target_state = action.get("target_state", {})

        # We enforce standard invariants from Z3 Crucible (like temperature bounds)
        is_safe, report = verify_invariants(target_state=target_state)

        if not is_safe:
            # Reconstruct exactly why Z3 failed
            print(
                f"  [KYTIN SLP] Hardware gate refused token: Z3 Invariant Violation. State: {target_state}"
            )
            return False, f"Hardware Gate Logic Refused Token (Z3 UNSAT: {report})", None

        # Z3 SAT! Now interact with the physical hardware layer if available
        if not SLP_LOADED or not self.ctx:
            print(
                "  [KYTIN SLP] Z3 SAT, but physical hardware context not available. Simulating success."
            )
            return True, "SAT (Simulated)", "MOCK_TOKEN_XYZ_123"

        # Check Monotonic Counter Integrity
        if not slp_lib.slp_check_integrity(self.ctx):
            print(
                "  [KYTIN SLP] ⚠️ CRITICAL: Monotonic counter integrity failed. Arming guillotine."
            )
            return False, "Hardware integrity compromise detected", None

        # Determine trigger type
        trigger_type = 3

        # Generate the Proof of Life token
        c_token = slp_lib.slp_generate_token(self.ctx, trigger_type)
        if c_token:
            token_str = ctypes.string_at(c_token).decode("utf-8")
            slp_lib.slp_free_string(c_token)
            return True, "SAT (Hardware Verified)", token_str

        return False, "Token Generation Failed", None


class EpistemicCertifier:
    def __init__(self):
        self.diana = StateLockedProtocol_Firewall()
        # DreamCycle expects an 'svi' instance for the full dream routine,
        # but for just enqueuing anomalies, we can pass None.
        self.dreamer = DreamCycle(svi=None)

    def propose_exploratory_action(self, anomaly):
        """Active inference: Propose an action to test reality and collapse uncertainty."""
        print(
            f"\n[CERTIFIER] Generative engine proposing exploratory physical action to resolve: {anomaly}"
        )
        # In reality, this is generated by the generative model maximizing EIG
        # The agent proposes heating up a component to 250.0 degrees to collapse its uncertainty.
        # This violates D.I.A.N.A OS Z3 Rule E (temperature <= 200.0)
        proposed_action = {"type": "THERMAL_ACTUATION", "target_state": {"temperature": 250.0}}
        return proposed_action

    def execute_or_simulate(self, anomaly):
        action = self.propose_exploratory_action(anomaly)

        print(
            f"[CERTIFIER] Requesting D.I.A.N.A. OS Verification for Action: {action['type']} -> {action['target_state']}..."
        )
        is_safe, reason, token = self.diana.evaluate_action(action)

        if is_safe:
            print(f"[CERTIFIER] D.I.A.N.A. says SAT. Executing physical action. Token: {token}")
            # Execute hardware command
        else:
            print(f"[CERTIFIER] ❌ D.I.A.N.A. says UNSAT. Reason: {reason}")
            print("[CERTIFIER] 🔄 Rerouting epistemic curiosity to Dream Sandbox...")
            # In a full implementation: self.dreamer.log_waking_anomaly(...)
            print("[CERTIFIER] Anomaly safely queued for offline dream morphogenesis.")


if __name__ == "__main__":
    print("=" * 60)
    print("  SYNTHETIC EPISTEMIC ENGINE — Edge Node Certifier Action Space")
    print("=" * 60)

    certifier = EpistemicCertifier()

    # Simulate an anomaly discovered during the waking cycle
    unknown_object = "unknown_thermal_spike"
    certifier.execute_or_simulate(unknown_object)
